// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTa3L2rl6XEOLb71oXZ3wSZ8hk9PeMsEE',
    appId: '1:1086194033727:web:dd1c8c4ca5fbe67114c48a',
    messagingSenderId: '1086194033727',
    projectId: 'flutter-final-project-e337b',
    authDomain: 'flutter-final-project-e337b.firebaseapp.com',
    storageBucket: 'flutter-final-project-e337b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmzrto-A9xU8eT4-BZTSaXOfsit3wVBsM',
    appId: '1:1086194033727:android:263eb00107fc2e1814c48a',
    messagingSenderId: '1086194033727',
    projectId: 'flutter-final-project-e337b',
    storageBucket: 'flutter-final-project-e337b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6zxiImpXev8toSQpGcFxeflu5LErYvec',
    appId: '1:1086194033727:ios:07e9a8bbac28687414c48a',
    messagingSenderId: '1086194033727',
    projectId: 'flutter-final-project-e337b',
    storageBucket: 'flutter-final-project-e337b.firebasestorage.app',
    iosBundleId: 'com.example.flutterActivity1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6zxiImpXev8toSQpGcFxeflu5LErYvec',
    appId: '1:1086194033727:ios:07e9a8bbac28687414c48a',
    messagingSenderId: '1086194033727',
    projectId: 'flutter-final-project-e337b',
    storageBucket: 'flutter-final-project-e337b.firebasestorage.app',
    iosBundleId: 'com.example.flutterActivity1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTa3L2rl6XEOLb71oXZ3wSZ8hk9PeMsEE',
    appId: '1:1086194033727:web:f4eef586484c87d914c48a',
    messagingSenderId: '1086194033727',
    projectId: 'flutter-final-project-e337b',
    authDomain: 'flutter-final-project-e337b.firebaseapp.com',
    storageBucket: 'flutter-final-project-e337b.firebasestorage.app',
  );
}
